services:
  submit:
    build:
      context: ./submit-app
    container_name: submit
    restart: unless-stopped
    env_file: .env
    environment:

      ## PUT THESE IN MAIN .ENV
      
      # url to joke service - sync calls
      JOKE_BASE_URL: http://${JOKE_PRIVATE_IP}:${JOKES_CONTAINER_PORT}

      # rabbitmq connection details - async calls
      AMQP_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      QUEUE_NAME: ${QUEUE_NAME}

      # port
      PORT: ${SUBMIT_CONTAINER_PORT}

      # file cache path inside container - mounted volume
      TYPES_CACHE_PATH: /cache/typeCache.json

    ports:
      - "${SUBMIT_PORT_INTERNAL}:${SUBMIT_CONTAINER_PORT}"
    volumes:
      - submit_types_cache:/cache


volumes:
  submit_types_cache:
